Repository bar-d/OP.GGCloneCoding, pull requests merged in 2022-10, with the labels that each got.

#1 LaunchScreen 구현
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GG Logo/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GG Logo/OP.GGLogo.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GG Logo/OP.GGLogo.imageset/OP.GGLogo.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GG Logo/OP.GGLogo.imageset/OP.GGLogo@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GG Logo/OP.GGLogo.imageset/OP.GGLogo@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Base.lproj/LaunchScreen.storyboard
Labels: feat

#2 LoadingView 커스텀 뷰 구현
  .gitignore
  OP.GGCloneCoding/OP.GGCloneCoding.xcodeproj/project.pbxproj
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/LoadingIndicator.json
  OP.GGCloneCoding/OP.GGCloneCoding/View/LoadingView.swift
Labels: feat

#3 BuilderPattern 적용
  OP.GGCloneCoding/OP.GGCloneCoding.xcodeproj/project.pbxproj
  OP.GGCloneCoding/OP.GGCloneCoding/Builder/ButtonBuilder.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Builder/ImageViewBuilder.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Common/LoadingView.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Main/View/MainTopView.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Main/View/MainViewController.swift
  OP.GGCloneCoding/OP.GGCloneCoding/View/LanguageButton.swift
  OP.GGCloneCoding/OP.GGCloneCoding/View/SummonerSearchButton.swift
Labels: feat, style, refactor

#4 하단 tab bar 구현
  OP.GGCloneCoding/OP.GGCloneCoding.xcodeproj/project.pbxproj
  OP.GGCloneCoding/OP.GGCloneCoding/Application/SceneDelegate.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ChampionIcon.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ChampionIcon.imageset/helmet (2).png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ChampionIcon.imageset/helmet (2)@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ChampionIcon.imageset/helmet (2)@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/CommunityIcon.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/CommunityIcon.imageset/lightUnselectedCommunity.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/CommunityIcon.imageset/lightUnselectedCommunity@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/CommunityIcon.imageset/lightUnselectedCommunity@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ESportsIcon.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ESportsIcon.imageset/lightUnselectedThrophy.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ESportsIcon.imageset/lightUnselectedThrophy@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/ESportsIcon.imageset/lightUnselectedThrophy@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/HomeIcon.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/HomeIcon.imageset/home-2.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/HomeIcon.imageset/home-2@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/HomeIcon.imageset/home-2@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/SettingsIcon.imageset/Contents.json
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/SettingsIcon.imageset/lightUnselectedSetting.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/SettingsIcon.imageset/lightUnselectedSetting@2x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Resource/Assets.xcassets/OP.GGIcon/SettingsIcon.imageset/lightUnselectedSetting@3x.png
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Main/View/TabBarController.swift
Labels: feat, update, add

#6 MainView 브랜치 내 SettingsView 구현부 적용
  OP.GGCloneCoding/OP.GGCloneCoding.xcodeproj/project.pbxproj
  OP.GGCloneCoding/OP.GGCloneCoding/Builder/ButtonBuilder.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Builder/HeaderViewBuilder.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Builder/ImageViewBuilder.swift
  OP.GGCloneCoding/OP.GGCloneCoding/PreviewHelpers/SwiftUIPreview.swift
  OP.GGCloneCoding/OP.GGCloneCoding/PreviewHelpers/SwiftUIPreviewController.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Common/HeaderView.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Common/Section/NavigationBarButton.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Main/View/TabBarController.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/Cell/Protocol/CellCustomizable.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/Cell/PushNotificationCell.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/Cell/SettingsCell.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/Section/SettingSection.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/SettingsStickyHeaderView.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/SettingsTableView.swift
  OP.GGCloneCoding/OP.GGCloneCoding/Scene/Settings/View/SettingsViewController.swift
Labels: feat, style, refactor, add
